di_user:
    resource: "@DIUserBundle/Resources/config/routing.yml"
    prefix:   /

di_platform:
    resource: "@DIPlatformBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/platform
    requirements:
        _locale: en|fr|ru

app:
    resource: '@AppBundle/Controller/'
    type: annotation

#login:
  #  path: /login
    #defaults:
      #  _controller: DIUserBundle:Security:login

#login_check:
 #   path: /login_check

 #logout:
   # path: /logout

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
